### ISSUE TITLE
Got a python error

### ISSUE THREAD

**Issue by Knovour** [kali/opencv-rust#11]
```python
--- stderr
/usr/lib/python3.5/re.py:203: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)
Traceback (most recent call last):
  File "gen_rust.py", line 1657, in <module>
    generator.gen(srcfiles, module, dstdir)
  File "gen_rust.py", line 1206, in gen
    self.add_decl(decl)
  File "gen_rust.py", line 1176, in add_decl
    FuncInfo(self, decl, namespaces=self.namespaces)
  File "gen_rust.py", line 467, in __init__
    raise NameError("class not found: " + self.classname)
NameError: class not found: cv
thread '<main>' panicked at 'explicit panic', /home/knovour/.cargo/registry/src/github.com-0a35038f75765ae4/opencv-0.2.0/build.rs:86
```

Should I need to downgrade the python version?

**Comment by kali** [comment]
You will need to have a python 2.7 somewhere, yes. python 2.x and python 3.x are not compatible, but most modern OS support having both installed at the same time.

I have changed the scripts so that they refer to "python2.7" instead of just "python". As far as I can tell, this will work on both macos and ubuntu. I can see you're using linux, but not which flavour. Tell me if 0.2.1 works for you.

**Comment by Knovour** [comment]
I am using Manjaro Linux, and the default python version is 3.5.

Version 0.2.1 seems working now, thank you!

**Comment by BartekHdd** [comment]
Hi. I'm using ubuntu 18.04 and I have (probably) the same problem, even though I have python 2.7 installed. What I should to do?
![zrzut ekranu z 2019-01-11 22-05-14](https://user-images.githubusercontent.com/24289073/51273850-020eea00-19ce-11e9-97cd-46c9f0c153ad.png)
