### ISSUE TITLE
Switch to a better license?

### ISSUE THREAD

**Issue by durin42** [kali/opencv-rust#18]
Hi! Any chance you could switch to some other license? MIT would give you what I assume you want[0], but has the benefit of being a reasonably respected license, whereas the WTFPL makes most lawyers nervous (see https://news.ycombinator.com/item?id=5733050#up_5733477 for some analysis if you're curious).

Thanks!

0: I'm assuming what you want is "go nuts, I don't care, don't sue me, thanks."

**Comment by kali** [comment]
I would prefer not to.

I'm tired of the whole law industry parasiting the IT economy. I am convinced that WTFPL make my intentions perfectly clear. If lawyers are nervous about it, my only assumption is, it's because there are not enough words in the licence text to fuck with it and make my intentions ambiguous. Also, I did not have to consult a lawyer to explain the license to me, so double loss for them.

As a matter of fact, this wrapper generator is not in a very good shape anyway, so the WTFPL license feels kinda right. If somebody wants to do something serious with it, the license will probably be the least of the issue.

Finally, I'm a pragmatist. If somebody comes to me with an actual use case or some productive contribution to the code and is only stopped by my license choice, I'll reconsider this stance. There are indeed acceptable alternatives, MIT being probably at the top of the list.

**Comment by durin42** [comment]
Well, I was hoping to do some tinkering in Rust with OpenCV, and you've got the best-looking bindings, but I won't touch WTFPL because it's a bad license. I hope you reconsider some day.

**Comment by dralley** [comment]
@kali The problem with WTFPL is precisely that it is *ambiguous*.  In particular:

* It's not explicit that you're free from warranty, meaning that, unlike basically all code ever written, you're on the hook for bugs and defects, just like a physical product.  WTFPL is the only software license I know of that doesn't do this.

* It's not explicit that the user can redistribute the software freely, which causes problems under certain definitions of copyright used by different countries.

I second @durin42 , MIT is a far better license.

**Comment by kali** [comment]
Here you go. This is me giving up, not convinced. I have other battle to fight. I think you guys have too much faith in the magical powers of "as is" written in capitals, but I'm so bored with this conversation...
